[files]
# Respect .ignore files.
ignore-dot = true
# Respect ignore files.
ignore-files = true
# Typos-specific ignore globs (gitignore syntax).
# NOTE: This setting is ignored when you pass the path directly on the command line, as cachix/git-hooks.nix does.
# To ignore those files, you must also exclude those directories via git-hooks.hooks.typos.settings.exclude.
extend-exclude = [
  "data/",
  "rime-data/",
]

[default]
# Check binary files as text.
binary = false
# Verify spelling in file names.
check-filename = true
# ignore some special identifiers(sha256, mac address, crypto keys, etc)
extend-ignore-re = [
  "iterm2",
  "iHgEIBYKACAWIQSizQe9ljFEyyclWmtVhZllwnQrSwUCZZ1T9wIdAAAKCRBVhZll", # crypto keys
  "noice",                                                            # noice.nvim
  "crypted-nixos",
  "daed",

  # catppuccin theme colors
  "11111b",
  "1e1e2e",
  "313244",
  "414356",
  "45475a",
  "585b70",
  "89b4fa",
  "94e2d5",
  "a6adc8",
  "a6e3a1",
  "bac2de",
  "cdd6f4",
  "f38ba8",
  "f5c2e7",
  "f5e0dc",
  "f9e2af",
  "fab387",
]
