# https://grafana.com/docs/grafana/latest/datasources/prometheus/
apiVersion: 1

datasources:
  - name: prometheus-homelab
    type: prometheus
    access: proxy
    # Access mode - proxy (server in the UI) or direct (browser in the UI).
    url: http://localhost:9090
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.49.0
      cacheLevel: "High"
      disableRecordingRules: false
      # As of Grafana 10, the Prometheus data source can be configured to query live dashboards
      # incrementally, instead of re-querying the entire duration on each dashboard refresh.
      # Increasing the duration of the incrementalQueryOverlapWindow will increase the size of every incremental query,
      # but might be helpful for instances that have inconsistent results for recent data.
      incrementalQueryOverlapWindow: 10m
